
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox5;

	private global::Gtk.DrawingArea drawingarea12;

	private global::Gtk.DrawingArea drawingarea13;

	private global::Gtk.VBox vbox4;

	private global::Gtk.DrawingArea drawingarea9;

	private global::Gtk.Label lblinicio;

	private global::Gtk.Entry entnombre;

	private global::Gtk.Entry entcontraseña;

	private global::Gtk.Button btniniciar;

	private global::Gtk.Button btnsalir;

	private global::Gtk.DrawingArea drawingarea15;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Label lblhora;

	private global::Gtk.Label lblhora1;

	private global::Gtk.DrawingArea drawingarea10;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.drawingarea12 = new global::Gtk.DrawingArea();
		this.drawingarea12.Name = "drawingarea12";
		this.vbox5.Add(this.drawingarea12);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.drawingarea12]));
		w1.Position = 1;
		// Container child vbox5.Gtk.Box+BoxChild
		this.drawingarea13 = new global::Gtk.DrawingArea();
		this.drawingarea13.Name = "drawingarea13";
		this.vbox5.Add(this.drawingarea13);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.drawingarea13]));
		w2.Position = 2;
		this.hbox1.Add(this.vbox5);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox5]));
		w3.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.drawingarea9 = new global::Gtk.DrawingArea();
		this.drawingarea9.Name = "drawingarea9";
		this.vbox4.Add(this.drawingarea9);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.drawingarea9]));
		w4.Position = 0;
		// Container child vbox4.Gtk.Box+BoxChild
		this.lblinicio = new global::Gtk.Label();
		this.lblinicio.Name = "lblinicio";
		this.lblinicio.LabelProp = global::Mono.Unix.Catalog.GetString("Inicio de sesión");
		this.vbox4.Add(this.lblinicio);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.lblinicio]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.entnombre = new global::Gtk.Entry();
		this.entnombre.CanFocus = true;
		this.entnombre.Name = "entnombre";
		this.entnombre.Text = global::Mono.Unix.Catalog.GetString("Nombre de usuario");
		this.entnombre.IsEditable = true;
		this.entnombre.InvisibleChar = '●';
		this.vbox4.Add(this.entnombre);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.entnombre]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.entcontraseña = new global::Gtk.Entry();
		this.entcontraseña.CanFocus = true;
		this.entcontraseña.Name = "entcontraseña";
		this.entcontraseña.Text = global::Mono.Unix.Catalog.GetString("Contraseña");
		this.entcontraseña.IsEditable = true;
		this.entcontraseña.Visibility = false;
		this.entcontraseña.InvisibleChar = '●';
		this.vbox4.Add(this.entcontraseña);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.entcontraseña]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.btniniciar = new global::Gtk.Button();
		this.btniniciar.CanFocus = true;
		this.btniniciar.Name = "btniniciar";
		this.btniniciar.UseUnderline = true;
		this.btniniciar.Label = global::Mono.Unix.Catalog.GetString("Iniciar sesión");
		this.vbox4.Add(this.btniniciar);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.btniniciar]));
		w8.Position = 4;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.btnsalir = new global::Gtk.Button();
		this.btnsalir.CanFocus = true;
		this.btnsalir.Name = "btnsalir";
		this.btnsalir.UseUnderline = true;
		this.btnsalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.vbox4.Add(this.btnsalir);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.btnsalir]));
		w9.Position = 5;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.drawingarea15 = new global::Gtk.DrawingArea();
		this.drawingarea15.Name = "drawingarea15";
		this.vbox4.Add(this.drawingarea15);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.drawingarea15]));
		w10.Position = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.lblhora = new global::Gtk.Label();
		this.lblhora.Name = "lblhora";
		this.lblhora.LabelProp = "";
		this.hbox6.Add(this.lblhora);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.lblhora]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.lblhora1 = new global::Gtk.Label();
		this.lblhora1.Name = "lblhora1";
		this.lblhora1.LabelProp = "";
		this.hbox6.Add(this.lblhora1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.lblhora1]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox4.Add(this.hbox6);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
		w13.Position = 7;
		w13.Expand = false;
		w13.Fill = false;
		this.hbox1.Add(this.vbox4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox4]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.drawingarea10 = new global::Gtk.DrawingArea();
		this.drawingarea10.Name = "drawingarea10";
		this.hbox1.Add(this.drawingarea10);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.drawingarea10]));
		w15.Position = 2;
		this.Add(this.hbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
